name: Release Workflow

env:
  RELEASE_COMMIT: ${{ github.sha }}
  GO_VERSION: "1.20"

on:
  push:
    branches:
      # TODO (hawflau): update to develop on launch
      - "dev-release-pipeline"
    paths:
      - "python-client/src/aws_ctk/version.py"
  workflow_dispatch:

jobs:
  # This job get the version from the version file and exports it for subsequent jobs to use
  get-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      RELEASE_VERSION: ${{ steps.release_version.outputs.RELEASE_VERSION }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          ref: ${{ env.RELEASE_COMMIT }}

      - name: Export release version
        id: release_version
        run: |
          RELEASE_VERSION=$(awk -F '"' '/_version = /{print $2}' python-client/src/aws_ctk/version.py)
          echo $RELEASE_VERSION
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> "$GITHUB_OUTPUT"

      - name: check version tag
        run: |
          echo $(git tag --list "v${{ steps.release_version.outputs.RELEASE_VERSION }}")
          if [ $(git tag --list "v${{ steps.release_version.outputs.RELEASE_VERSION }}") ]
          then
            echo "Tag v${{ steps.release_version.outputs.RELEASE_VERSION }} already exists. Exiting"
            exit 1
          fi

  # This job runs tests and linting before building artifacts
  quality-check:
    needs: [get-version]
    uses: ./.github/workflows/reusable_quality-check.yml
    with:
      ref: ${{ github.sha }} # cannot use env
    secrets:
      CI_IAM_ROLE_ARN: ${{ secrets.CI_IAM_ROLE_ARN }}

  # This job builds python client artifacts and publishes them to PyPi
  # It returns the provenance information for subsequent jobs to use.
  release-python-client:
    needs: [quality-check]
    uses: ./.github/workflows/reusable_release-python-client.yml
    with:
      ref: ${{ github.sha }} # cannot use env
      artifact_name: "python-client-artifacts"
      # TODO (hawflau): remove the line below on launch
      skip_pypi: true

  # This job creates git tag and a draft release on GitHub
  create-tag:
    needs: [get-version, quality-check, release-python-client]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          ref: ${{ env.RELEASE_COMMIT }}

      - name: Git client setup and refresh tip
        id: setup-git
        run: |
          git config user.name "AWS CTK bot"
          git config user.email "aws-ctk-feedback@amazon.com"
          git config remote.origin.url >&-

      - name: Create Git Tag and draft release
        env:
          RELEASE_VERSION: ${{ needs.get-version.outputs.RELEASE_VERSION }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a v"${RELEASE_VERSION}" -m "release_version: v${RELEASE_VERSION}"
          git push origin v"${RELEASE_VERSION}"
          gh release create v"${RELEASE_VERSION}" --draft --generate-notes --title "Release version: v${RELEASE_VERSION}"

      - name: Upload provenance
        id: upload-provenance
        uses: ./.github/actions/upload-release-provenance
        with:
          release_version: ${{ needs.get-version.outputs.RELEASE_VERSION }}
          provenance_name: ${{ needs.release-python-client.outputs.provenance_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
